apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: {{ .Values.global.repository }}/registry:{{ .Values.global.imageTag }}
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: data
            mountPath: /var/lib/registry
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: registry-storage
