apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  {{- if .Values.global.storage.class }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storage.class | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- if .Values.server.persistentVolume.annotations }}
{{ toYaml .Values.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}
spec:
  accessModes:
{{- range .Values.server.persistentVolume.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.global.grafana.persistentVolume | quote }}
