{{- if .Values.aggregator.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "aggregator.fullname" . }}

  labels:
    app: {{ template "fluentd.fullname" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: {{ template "aggregator.fullname" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  minReadySeconds: 5
  progressDeadlineSeconds: 15
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "100%"
  template:
    metadata:
      labels:
        app: {{ template "fluentd.fullname" . }}
        component: {{ template "aggregator.fullname" . }}
        release: "{{ .Release.Name }}"
      annotations:
        {{ template "fluentd.fullname" . }}-config/sha256sum: {{ include (print $.Template.BasePath "/fluentd-configmap.yaml") . | sha256sum }}
        {{ template "fluentd.fullname" . }}-secrets/sha256sum: {{ include (print $.Template.BasePath "/fluentd-secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: proxy
        image: "{{ .Values.global.repository }}/haproxy:{{ .Values.global.imageTag }}"
        args:
          - /usr/local/sbin/haproxy-systemd-wrapper
          - -f
          - /etc/haproxy/haproxy.cfg
          - -p
          - /var/run/haproxy-private.pid
        ports:
          - name: https
            containerPort: 443
        volumeMounts:
          - name: certs
            mountPath: "/data/cert"
          - name: etc-ssl
            mountPath: "/etc/ssl"
          - name: proxy-config
            mountPath: "/etc/haproxy"
      - name: fluentd
        image: "{{ .Values.global.repository }}/fluentd:{{ .Values.global.imageTag }}"
        command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins"]
        env:
{{- if not .Values.global.minikube.enabled }}
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_MASTER
          value: "127.0.0.1"
{{- end }}
        - name: FLUENTD_CONFIG
          value: fluentd-aggregator.conf
        ports:
        - name: fwd-input
          containerPort: 24224
          protocol: TCP
        - name: fwd-input-udp
          containerPort: 24224
          protocol: UDP
        - name: prom-metrics
          containerPort: 24231
          protocol: TCP
        - name: monitor-agent
          containerPort: 24220
          protocol: TCP
        - name: http-input
          containerPort: 9880
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 24224
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: fluentd-secrets
          mountPath: /fluentd/secrets
      volumes:
      - name: etc-ssl
        hostPath:
          path: /etc/ssl
      - name: certs
        hostPath:
          path: /data/cert
      - name: proxy-config
        configMap:
          name: fluentd-proxy-config
      - name: fluentd-config
        configMap:
          name: {{ template "fluentd.fullname" . }}-config
      - name: fluentd-secrets
        secret:
          secretName: {{ template "fluentd.fullname" . }}-secrets
      # Give the aggregator ample time to flush it's logs
      terminationGracePeriodSeconds: 160
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- end }}
