info:
  version: 1.5.0
  description: подсистема "Идентификации и аутентификации"

logging:
  level:
    org.dclou.platform: TRACE
    org.springframework: INFO

spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

eureka:
  instance:
      prefer-ip-address: false


server:
  port: 80
  context-path: /auth
  session:
    cookie:
      name: JSESSIONIDAUTHSRV
  use-forward-headers: true

security:
  sessions: always
  user:
    password: password
  basic:
    enabled: false
  ignored: ${management.context-path},${management.context-path}/**
