apiVersion: v1
kind: Service
metadata:
  name: order
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ "/manage/prometheus" | .Values.metrics.path }}
    prometheus.io/port: {{ .Values.metrics.port }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: order
      port: 80
      targetPort: 80
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
