#Common DEFAULT settings
spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

  sleuth:
    enabled: true
    stream:
      enabled: true
    sampler:
      percentage: 1

  # sleuth-zipkin async messaging
  rabbitmq:
    addresses: platform-rabbitmq.platform.svc.cluster.local
    username: guest
    password: guest

encrypt:
  failOnError: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    region: default
    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka/
      defaultZone: http://discovery-service.platform.svc.cluster.local:8761/eureka/
    availabilityZones:
      default: defaultZone
  instance:
      hostname: ${spring.application.name}
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 30
      leaseExpirationDurationInSeconds: 60
      securePortEnabled: false
      nonSecurePortEnabled: true
      metadataMap:
        management.context-path: ${server.context-path}${management.context-path}
        management.port: ${management.port}
        instanceId: ${spring.application.name}:${random.value}
      homePageUrl: http://${eureka.instance.hostname}:${management.port}/
      status-page-url-path: ${server.context-path}${management.context-path}/info
      health-check-url-path: ${server.context-path}${management.context-path}/health
management:
  port: ${server.port}
  security.enabled: false
  context-path: /manage

# Turn off the basic endpoint security (helps with [Registry]
security:
  basic:
    enabled: false
  ignored: ${management.context-path},${management.context-path}/**

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

springfox.documentation.swagger.v2.path: /api-docs
