apiVersion: v1
description: GitLab running on Kubernetes
name: gitlab-omnibus
version: 0.1.1
tillerVersion: ">=2.5.0"
home: https://about.gitlab.com
sources:
- http://docs.gitlab.com/ce/install/kubernetes/
- https://gitlab.com/charts/charts.gitlab.io
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
