kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- if .Values.global.storage.class }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storage.class | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}

spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.global.rabbitmq.persistentVolume | quote }}
