{{- if .Values.kubeStateMetrics.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.kubeStateMetrics.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.kubeStateMetrics.fullname" . }}

spec:
  replicas: {{ .Values.kubeStateMetrics.replicaCount }}
  template:
    metadata:
    {{- if .Values.kubeStateMetrics.podAnnotations }}
      annotations:
{{ toYaml .Values.kubeStateMetrics.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "prometheus.name" . }}
        component: "{{ .Values.kubeStateMetrics.name }}"
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: etc-ssl
          hostPath:
            path: /etc/ssl
        - name: certs
          hostPath:
            path: /data/cert
        - name: proxy-config
          configMap:
            name: prometheus-proxy-config
      containers:
        - name: proxy
          image: "{{ .Values.global.repository }}/haproxy:{{ .Values.global.imageTag }}"
          args:
            - /usr/local/sbin/haproxy-systemd-wrapper
            - -f
            - /etc/haproxy/haproxy.cfg
            - -p
            - /var/run/haproxy-private.pid
          ports:
            - name: https
              containerPort: 443
          volumeMounts:
            - name: certs
              mountPath: "/data/cert"
            - name: etc-ssl
              mountPath: "/etc/ssl"
            - name: proxy-config
              mountPath: "/etc/haproxy"
        - name: {{ template "prometheus.name" . }}-{{ .Values.kubeStateMetrics.name }}
          image: "{{ .Values.global.repository }}/kube-state-metrics:{{ .Values.global.imageTag }}"
{{- if not .Values.global.minikube.enabled }}
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "127.0.0.1"
{{- end }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.kubeStateMetrics.resources | indent 12 }}
    {{- if .Values.kubeStateMetrics.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kubeStateMetrics.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 9 }}
