apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  {{- if .Values.global.storage.class }}
    volume.beta.kubernetes.io/storage-class: "{{ .Values.global.storage.class }}"
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- if .Values.server.persistentVolume.annotations }}
{{ toYaml .Values.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.server.fullname" . }}

spec:
  accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.global.prometheus.serverVolume | quote }}
