apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}-config
data:
{{ toYaml .Values.sonar | indent 2 }}
