{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $servicePort := .Values.httpPort -}}
{{- $ingress_suffix := .Values.global.ingress.suffix }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}.{{ $ingress_suffix }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.name}}
              servicePort: {{ $servicePort }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
