apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 2G
spec:
  rules:
  - host: gitlab.{{ .Values.global.ingress.suffix }}
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
  - host: registry.{{ .Values.global.ingress.suffix }}
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 8105
---
