apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  external_scheme: {{ .Values.global.gitlab.schema }}
  external_hostname: gitlab.{{ .Values.global.ingress.suffix }}
  registry_external_scheme: {{ .Values.global.gitlab.schema }}
  registry_external_hostname: registry.{{ .Values.global.ingress.suffix }}
  mattermost_external_scheme: {{ .Values.global.gitlab.schema }}
  mattermost_external_hostname: mattermost.{{ .Values.global.ingress.suffix }}
  mattermost_app_uid: {{ .Values.mattermostAppUID }}
  postgres_db: {{ .Values.postgresql.postgresDatabase | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.redisPassword | b64enc | quote }}
  mattermost_app_secret: {{ .Values.mattermostAppSecret | b64enc | quote }}
{{- if .Values.gitlabEELicense }}
  gitlab_ee_license: {{ .Values.gitlabEELicense | b64enc | quote }}
{{- end }}
