apiVersion: v1
kind: Service
metadata:
  name: config-platform-service
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: config-platform-service
      port: 80
      targetPort: 80
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
