image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

stages:
  - build
  - test
  - package

compile:
  stage: build
  script: |
    mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script: |
    mvn $MAVEN_CLI_OPTS test

package:
  only: 
    - master
    - testing
  stage: package
  script: |
    mvn $MAVEN_CLI_OPTS package
  artifacts:
    expire_in: 1 day
    paths:
      - target/*.jar
