apiVersion: v1
kind: Secret
metadata:
  name: runner-secrets
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if not .Values.global.gitlab.runnerSecrets.id_rsa }}
  "id_rsa": ""
{{- end -}}
{{- range $k, $v := .Values.global.gitlab.runnerSecrets -}}
  {{- if $v.verbatim }}
  "{{ $k }}": {{ $v.content | quote }}
  {{- else -}}
  {{- if $v.content }}
  "{{ $k }}": {{ $v.content | b64enc | quote }}
  {{- end -}}
  {{- end -}}
{{ end }}
